### PR TITLE
add insight blog styles

### PR DESCRIPTION
**Pull request by samuelopra**
**Authoring edits:**

1. Changed description of insights to an h3
2. Added insight banner section
3. Added insight thumbnail section
4. Added insight content section

#72

Test URLs:
- Before: https://main--maestro--hlxsites.hlx.page/insights/feeding-the-data-hungry
- After: https://issue-72--maestro--hlxsites.hlx.page/insights/feeding-the-data-hungry

https://issue-72--maestro--hlxsites.hlx.page/insights/maestro-webinar

### CODE REVIEW

**Comment by kunwarsaluja** [comment]
@samuelopra is this ready for review ? Can you move all this under the insights.css if all is specific to blog pages or is it generic enough to be included in global styles.css ?

Also, Can you refactor to use global vars wherever possible

Check on an actual mobile phone browser too. I see abunch of issues (vimeo video isnt adapting to media queries, the quoted content is overflowing etc.)

**Comment by samuelopra** [comment]
> @samuelopra is this ready for review ? Can you move all this under the insights.css if all is specific to blog pages or is it generic enough to be included in global styles.css ?
> 
> Also, Can you refactor to use global vars wherever possible
> 
> Check on an actual mobile phone browser too. I see abunch of issues (vimeo video isnt adapting to media queries, the quoted content is overflowing etc.)

the video actually behaves the same on the main site

**Comment by kunwarsaluja** [comment]
IMG_1967
This is how it looks on my phone browser. I think we need to fix so it adapts to the layout

**Comment by kunwarsaluja** [comment]
@samuelopra  Few other things noticed - 
- Image under the teaser block might need some tweaking so it looks similar to live site
- global variables to be used wherever possible in insights.css
- quoted content styling is missing in content

**Review by kunwarsaluja — APPROVED** [review]

**Pull request merged**
